added changelog/master.xml directory to resourcesec added the ability to grant users administrator status
cmps-department/charity-service pull request #12
Opened 2023-05-02 10:01 UTC by sanv1ad

2023-05-02 22:19 UTC, MartianDill requested changes
Requested change on 

- [ ] SampleController.java

- [x] master.xml

2023-05-02 22:19 UTC, MartianDill commented on src/main/java/cmps/charityservice/SampleController.java
> -import org.springframework.web.bind.annotation.RestController;
You have removed these import lines 4-7, even though they are referenced in lines 11-13 and 16
Delete the lines that refer to them entirely if they are not needed or restore the deleted imports

2023-05-02 22:19 UTC, MartianDill commented on src/main/resources/changelog/master.xml
> +</databaseChangeLog>
In my branch I also created a similar file for myself, in my version it looked like this:
```java
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
        http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd">
    <includeAll path="initial_schema" relativeToChangelogFile="true"/>
</databaseChangeLog>
``` 
Maybe you should add lines with xml version and 'includeAll' too

2023-05-03 12:01 UTC, Misha999777 approved these changes
Added some fixes, let's discuss them at the next meeting

2023-05-03 12:02 UTC, merged